//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarbaz.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garrison
    {
        public int ID { get; set; }
        public string Garrison1 { get; set; }
        public string GarrisonForce { get; set; }
        public string Commander { get; set; }
        public string CommanderGrade { get; set; }
        public string StaffCommander { get; set; }
        public string StaffCommanderGrade { get; set; }
        public string SoldiersCommander { get; set; }
        public string SoldiersCommanderGrade { get; set; }
    }
}
