//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarbaz.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leavings
    {
        public long ID { get; set; }
        public int SoldierID { get; set; }
        public string ExitDate { get; set; }
        public string EnteranceDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public string User { get; set; }
        public Nullable<int> Estehghaghi { get; set; }
        public Nullable<int> Tashvighi { get; set; }
        public Nullable<int> Esterahat { get; set; }
        public Nullable<int> Saati { get; set; }
        public Nullable<int> Estelaji { get; set; }
        public Nullable<int> Toorahi { get; set; }
        public string Date { get; set; }
    
        public virtual properties properties { get; set; }
    }
}
