//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarbaz.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoldierEntities1 : DbContext
    {
        public SoldierEntities1()
            : base("name=SoldierEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Farar> Farar { get; set; }
        public virtual DbSet<Garrison> Garrison { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Leavings> Leavings { get; set; }
        public virtual DbSet<properties> properties { get; set; }
        public virtual DbSet<Raste> Raste { get; set; }
        public virtual DbSet<TashvighTanbih> TashvighTanbih { get; set; }
        public virtual DbSet<Tbl_Ostan> Tbl_Ostan { get; set; }
        public virtual DbSet<Tbl_Shahrestan> Tbl_Shahrestan { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
    }
}
