//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarbaz.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TashvighTanbih
    {
        public int ID { get; set; }
        public Nullable<int> SoldierID { get; set; }
        public string Type { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string User { get; set; }
        public string Commander { get; set; }
        public string Used { get; set; }
    }
}
