//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarbaz.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Shahrestan
    {
        public int ID { get; set; }
        public Nullable<int> OstanID { get; set; }
        public string Title { get; set; }
    
        public virtual Tbl_Ostan Tbl_Ostan { get; set; }
    }
}
